name: msdfgen Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - feature/automated-build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        ./dependencies.sh
      shell: bash
      working-directory: scripts
    - name: Build
      run: |
        ./build.sh
      working-directory: ./scripts
    - name: Collect artifacts Windows
      run: |
        echo "ARTIFACT_DIRS=$(ls)" >> $env:GITHUB_ENV
      if: matrix.os == 'windows-latest'
    - name: Collect artifacts Linux
      run: |
        echo "ARTIFACT_DIRS=$(ls)" >> $GITHUB_ENV
      if: matrix.os == 'ubuntu-latest'
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_DIRS }}.zip
        path: bin/complete/${{ env.ARTIFACT_DIRS }}