name: msdfgen Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - feature/automated-build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        ./dependencies.sh
      shell: bash
      working-directory: scripts
    - name: Build
      run: |
        ./build.sh
      working-directory: ./scripts
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          bin/complete/*.tar.gz
          bin/complete/*.zip
#    - name: Collect artifacts Windows
#      run: |
#        echo "ARTIFACT_DIRS=$(ls -d $PWD/* | xargs)" >> $env:GITHUB_ENV
#      working-directory: ./bin/complete/
#      if: matrix.os == 'windows-latest'
#    - name: Collect artifacts Linux
#      run: |
#        echo "ARTIFACT_DIRS=$(ls -d $PWD/* | xargs)" >> $GITHUB_ENV
#      working-directory: ./bin/complete/
#      if: matrix.os == 'ubuntu-latest'
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Prepare for Release
      run: |
        git describe --exact-match --tags HEAD 2> /dev/null &&  echo "IS_RELEASE_TAG=True" >> $GITHUB_ENV || true
        echo "RELEASE_TAG_VERSION=$(git describe --tag)" >> $GITHUB_ENV
      shell: bash
    - name: Check release
      run: |
        echo "Is release: ${{ env.IS_RELEASE_TAG }}"
      shell: bash
    - uses: actions/download-artifact@v2
      with:
        name: artifacts
        path: artifacts
    - uses: "marvinpinto/action-automatic-releases@latest"
      if: env.IS_RELEASE_TAG=='True'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "${{ env.RELEASE_TAG_VERSION }}"
        files: |
          artifacts/*