name: msdfgen Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - feature/automated-build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    outputs:
      RELEASE_TAG_VERSION: ${{ steps.release_prep.outputs.RELEASE_TAG_VERSION }}
      IS_RELEASE_TAG: ${{ steps.release_prep.outputs.IS_RELEASE_TAG }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        ./dependencies.sh
      shell: bash
      working-directory: scripts
    - name: Build
      run: |
        ./build.sh
      working-directory: ./scripts
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          bin/complete/*.tar.gz
          bin/complete/*.zip
    - name: Prepare for Release
      id: release_prep
      run: |
        git describe --exact-match --tags HEAD 2> /dev/null &&  IS_RELEASE_TAG=True
        RELEASE_TAG_VERSION=$(git describe --tag)
        
        echo "::set-output name=RELEASE_TAG_VERSION::$RELEASE_TAG_VERSION"
        echo "::set-output name=IS_RELEASE_TAG::$IS_RELEASE_TAG"
        
      shell: bash
#    - name: Collect artifacts Windows
#      run: |
#        echo "ARTIFACT_DIRS=$(ls -d $PWD/* | xargs)" >> $env:GITHUB_ENV
#      working-directory: ./bin/complete/
#      if: matrix.os == 'windows-latest'
#    - name: Collect artifacts Linux
#      run: |
#        echo "ARTIFACT_DIRS=$(ls -d $PWD/* | xargs)" >> $GITHUB_ENV
#      working-directory: ./bin/complete/
#      if: matrix.os == 'ubuntu-latest'
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifacts
        path: artifacts
    - uses: "marvinpinto/action-automatic-releases@latest"
      if: needs.build.outputs.IS_RELEASE_TAG=='True'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "${{ needs.build.outputs.RELEASE_TAG_VERSION }}"
        files: |
          artifacts/*