name: msdfgen Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - feature/automated-build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Create build directories
      run: |
        mkdir bin/minimal
        mkdir bin/openmp
        mkdir tools
    - name: Install VCPKG
      run: |
        git clone https://github.com/microsoft/vcpkg
        ./vcpkg/bootstrap-vcpkg.bat
      working-directory: tools
      if: matrix.os == 'windows-latest'
    - name: Install Windows dependencies
      run: |
        tools/vcpkg/vcpkg install freetype
        tools/vcpkg/vcpkg install freetype:x64-windows
        tools/vcpkg/vcpkg integrate install
      shell: bash
      if: matrix.os == 'windows-latest'
    - name: Read Tag
      run: |
        echo "RELEASE_VERSION=$(git describe --tags)" >> $GITHUB_ENV
        echo $GITHUB_ENV
    - name: Build minimal
      run: |
        cmake ../.. -DMSDFGEN_BUILD_MSDFGEN_STANDALONE=ON -DMSDFGEN_USE_CPP11=ON
        cmake --build . --config Release -j 3
      working-directory: ./bin/minimal
    - name: Create minimal package
      run: |
        mkdir complete
        cp msdfgen complete/ 2>/dev/null || :
        cp msdfgen.exe complete/ 2>/dev/null || :
      working-directory: ./bin/minimal
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: msdfgen-${{ env.RELEASE_VERSION }}-minimal.zip
        path: bin/minimal/complete