name: msdfgen Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - feature/automated-build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install VCPKG
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v6
      with:
        setupOnly: true
        vcpkgGitCommitId: ec6fe06
      if: matrix.os == 'windows-latest'
    - name: Install Windows dependencies
      run: |
        $VCPKG_ROOT/vcpkg install freetype
      shell: bash
      if: matrix.os == 'windows-latest'
    - name: Read Tag
      run: |
        echo "RELEASE_VERSION=$(git describe --tags)" >> $GITHUB_ENV
        echo $GITHUB_ENV
    - name: Create build directories
      run: |
        mkdir minimal
        mkdir openmp
      working-directory: ./bin

    - name: Build minimal
      run: |
        cmake ../.. -DMSDFGEN_BUILD_MSDFGEN_STANDALONE=ON -DMSDFGEN_USE_CPP11=ON
        cmake --build . --config Release -- -j 3
        zip
      working-directory: ./bin/minimal
    - name: Create minimal package
      run: |
        mkdir complete
        cp msdfgen complete/ | true
        cp msdfgen.exe complete/ | true
      working-directory: ./bin/minimal
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: msdfgen-${{ env.RELEASE_VERSION }}-minimal.zip
        path: bin/minimal/complete