name: msdfgen Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - feature/automated-build
jobs:
  build:
    env:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Read Tag
      run: |
        echo "RELEASE_VERSION=$(git describe --tags)" >> $GITHUB_ENV
        echo $GITHUB_ENV
    - name: Create build directories
      run: |
        mkdir minimal
        mkdir openmp
      working-directory: ./bin
    - name: Build minimal
      run: |
        cmake ../.. -DMSDFGEN_BUILD_MSDFGEN_STANDALONE=ON -DMSDFGEN_USE_CPP11=ON
        cmake --build . --config Release -- -j 3
        zip
      working-directory: ./bin/minimal
    - name: Create minimal package
      run: |
        mkdir complete
        cp msdfgen* complete/
      working-directory: ./bin/minimal
    - uses: actions/upload-artifact@v2
      with:
      name: msdfgen-${{ env.RELEASE_VERSION }}-minimal
      path: bin/minimal/complete