name: msdfgen Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - feature/automated-build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        ./dependencies.sh
      shell: bash
      working-directory: scripts
    - name: Build
      run: |
        ./build.sh
      working-directory: ./scripts
    - name: Collect artifacts Windows
      run: |
        echo "ARTIFACT_DIRS=$(ls -d $PWD/* | xargs)" >> $env:GITHUB_ENV
      working-directory: ./bin/complete/
      if: matrix.os == 'windows-latest'
#    - name: Collect artifacts Linux
#      run: |
#        echo "ARTIFACT_DIRS=$(ls -d $PWD/* | xargs)" >> $GITHUB_ENV
#      working-directory: ./bin/complete/
#      if: matrix.os == 'ubuntu-latest'
    - name: Prepare for Release
      run: git describe --exact-match --tags HEAD &&  echo "IS_RELEASE_TAG='True')" >> $env:GITHUB_ENV
      if: matrix.os == 'windows-latest'
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: bin/complete/*
